WHITESPACE = _{ " " | "\t" | "\n" | "\r" }

identifier = @{
    LETTER ~ (LETTER | NUMBER | "_")*
}

type_ = {
    (identifier ~ ("[]")?)
}

keyword_extern = @{"extern"}
keyword_export = @{"export"}

expression_literal_string = @{"\"" ~ (!"\"" ~ ANY)* ~ "\""}

expression_literal = {
    expression_literal_string
}

expression_function_call = {
    identifier ~ "(" ~ (expression ~ ("," ~ expression)* ~ ","?)? ~ ")"
}

expression = {
    expression_function_call 
    | expression_literal
}

statement = { expression ~ ";" }

argument = { identifier ~ ":" ~ type_ }
argument_list = _{ argument ~ ("," ~ argument_list)? ~ ","? }

function_body = { ("{" ~ statement* ~ "}") | keyword_extern ~ ";" }

function_declaration = {
    (keyword_export)? ~ "fn" ~ identifier ~ "(" ~ argument_list? ~ ")" ~ ":" ~ type_ ~ function_body
}

import = {"import" ~ identifier ~ ("::" ~ identifier)* ~ ";"}

source_file = {
   SOI ~ import* ~ function_declaration* ~ EOI
}
